source "https://rubygems.org"
gem "flickraw"
gem "nokogiri"
gem "curb"
gem "image_sorcery", ">=1.1.0"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-r18n"
gem "rubyzip"
gem "haml"
gem "sass"
gem "gattica", :git => "git://github.com/chrisle/gattica.git"
gem "redis"
gem "hiredis"
