source "https://rubygems.org"
gem "flickraw"
gem "nokogiri"
gem "curb"
gem "image_sorcery", ">=1.1.0"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-r18n"
gem "rubyzip", '>=1.0'
gem "haml"
gem "sass"
gem "exifr"
